### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by pascalw** [Q42/q42.nl#112]
Hello Q42ers,

just a heads up; your RSS feed is broken.

```shell
$ curl -I http://blog.q42.nl/rss
HTTP/1.1 301 Moved Permanently
Server: nginx/1.2.1
Date: Wed, 19 Aug 2015 21:20:02 GMT
Content-Type: text/html
Content-Length: 184
Connection: keep-alive
Location: http://q42.nl/blog
```

Call me old fashioned but I still prefer RSS over Twitter for following blogs :blush:

**Comment by Primigenus** [comment]
Thanks @pascalw!

**Comment by pascalw** [comment]
Thanks! :+1: Small nitpick; the entries in that feed point to Tumbler, not q42.nl. Good enough for me though :-)
