### ISSUE TITLE
Fix dynamic gradients

### ISSUE THREAD

**Issue by guidobouman** [Q42/q42.nl#116]
Currently Gradients don't flow well with the colors from the color picker. Lets use an opaque solid color with different styles of gradient overlays.

For example: `linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0.4) 100%);`

**Comment by Primigenus** [comment]
Take a look at the code: https://github.com/Q42/q42.nl/blob/develop/to-become-packages/headerlights/client/template.headerlights.coffee#L31

What would you change?
