### ISSUE TITLE
Animation on loading /projecten

### ISSUE THREAD

**Issue by afkatja** [Q42/q42.nl#125]
On load /projecten or /projects, the first content block is jumping from top to its place. Looks like a FOUC.

Tested on Macbook Pro / Chrome latest.

Screen recording here:

https://drive.google.com/file/d/0B5WjynG_5a8JS29pZlFmQXRZWkk/view?usp=sharing

**Comment by Primigenus** [comment]
It's hard to fix conclusively due to the use of `position: absolute`, but I set a min-height on the container. Does it work a little better now?

**Comment by afkatja** [comment]
This visually fixes the issue. Maybe try one of the solutions RJ offered? Or the library by TimS?

**Comment by Primigenus** [comment]
Will take a look at a more longterm fix and close this issue for now.
