### ISSUE TITLE
Enable HSTS

### ISSUE THREAD

**Issue by chees** [Q42/q42.nl#139]
Apparently redirecting http to https takes a long time, so to tell browsers we are https only we can add a hsts header. See https://https.cio.gov/hsts/

Once we've done that we can add our site to this list:
https://hstspreload.appspot.com/

After that browsers will connect to https right away instead of trying http first.

**Comment by Primigenus** [comment]
I looked at this before and concluded that HSTS isn't really designed for a website like ours. It's more meant for high traffic, very visible sites. Read https://hstspreload.appspot.com/ and check the conditions chapter, which explains that it takes months for the HSTS preload list to filter down to Chrome, and it's very hard to make changes once you're on there.

So I don't think we should get into this.
