### ISSUE TITLE
Reblogs don't show up on homepage

### ISSUE THREAD

**Issue by lukasvan3l** [Q42/q42.nl#150]
it's may 12th and the april fool's day joke is still on the homepage :(

I propose to put the reblog articles on the homepage, when you click on them you go to q42.com/blog/ID where you can read our excerpt followed by a big button "READ THE ORIGINAL ARTICLE".

**Comment by Primigenus** [comment]
Fixed in 54ddb456c9290679011fac954e9eb15c597f7e40
