### ISSUE TITLE
Blogposts unavailable in tools like Pocket

### ISSUE THREAD

**Issue by Jpunt** [Q42/q42.nl#65]
I assume it's because of the async rendering of Meteor, but I can't add a blogpost to [Pocket](http://getpocket.com) and read it later. I'm not sure how this works in competitors like Instapaper though. I remember hearing something about a new pre-rendering-enigne in Meteor, will this fix this issue automatically?

**Comment by Primigenus** [comment]
@Jpunt The Q-site now supports prerender.io. Does that fix the issue?

**Comment by Jpunt** [comment]
Nope: 
![screen shot 2016-04-25 at 10 14 34](https://cloud.githubusercontent.com/assets/190501/14777657/c3e18fdc-0ace-11e6-8485-ed03557c0d64.png)

Instapaper does it right by the way. I guess you'd really need SSR if you want full coverage of these kind of tools.

**Comment by Primigenus** [comment]
OK. After looking around, it seems like Pocket doesn't adhere to AJAX crawling spec or specify a user agent, so prerender.io doesn't get activated either. If we run into a way to address this, we can fix it, but closing for now.
