### ISSUE TITLE
Employee gifs disappear after filtering

### ISSUE THREAD

**Issue by ontzettend** [Q42/q42.nl#89]
Filtering employee list makes the employee images disappear. After first filter, image stays intact. But when employees which weren't part of the first filter return, their image is blank.

![image](https://cloud.githubusercontent.com/assets/8337968/5629534/f5bbcd14-95b4-11e4-9b26-762f1de1eef4.png)

**Comment by Primigenus** [comment]
Was already (just) fixed in 36f97359 :D
