### ISSUE TITLE
/over-q42 asks for location

### ISSUE THREAD

**Issue by sjoerdvisscher** [Q42/q42.nl#92]
... and doesn't seem to do anything with it?

**Comment by Primigenus** [comment]
It uses it to determine routing on the map when you click on a pin.

Could this be clearer?

**Comment by sjoerdvisscher** [comment]
At least wait until someone clicks the link before we request the location. (Try it in safari, it's *really* annoying) And then maybe also make it work on the links below Bereikbaarheid?

**Comment by Primigenus** [comment]
Fixed in 165b8b5
