### ISSUE TITLE
Meteor.users collection public

### ISSUE THREAD

**Issue by lukasvan3l** [Q42/q42.nl#95]
This can be quite personal data, let's not publish.

![screen shot 2015-01-29 at 9 15 49](https://cloud.githubusercontent.com/assets/169870/5954443/ace136de-a797-11e4-8579-403f7b156df5.png)

**Comment by Primigenus** [comment]
This is by design. We only publish the data we need to show a person's name and picture next to their comment (on our blog) or their chat message (in the Slack integration). No private user data is published.
